project_id = "vjxssuywneheecuirxwb"

[functions.send-contact-email]
verify_jwt = false

[functions.reddata-chat]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-chat-notification]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.request-whatsapp-reset]
verify_jwt = false

[functions.validate-reset-code]
verify_jwt = false